### ISSUE TITLE
Unsupported language feature on Node.js 6

### ISSUE THREAD

**Issue by garycourt** [lxzxl/koa-i18next-middleware#4]
In koa-i18next-middleware v1.1.4 on Node.js v6.10.3, the follow error is being thrown:

```
node_modules/koa-i18next-middleware/dist/index.js:8
var LanguageDetector = exports.LanguageDetector = _koaI18nextDetector2.default;function getHandler(i18next, options = {}) {return async function (ctx, next) {
```

This is because this version of Node.js (which is currently LTS) does not support async functions.

You likely need to adjust your `.babelrc` file to target version 6.

**Comment by lxzxl** [comment]
@garycourt , sorry, this lib is simply aimed for Koa2 with async function enabled in nodejs.
