### ISSUE TITLE
Undefined variable `i`

### ISSUE THREAD

**Issue by garycourt** [lxzxl/koa-i18next-middleware#5]
https://github.com/lxzxl/koa-i18next-middleware/blob/aca460176836cd86258ee88b67b920c46dc2d1ab/src/index.js#L11

This line is referencing undefined variable `i`. I suspect the line is supposed to be written as:

```
if (!ignores.some(ignore => ctx.path.includes(ignore))) {
```

**Comment by lxzxl** [comment]
fixed, thanks!
