### ISSUE TITLE
TypeError: i18m.LanguageDetector.addDetector is not a function

### ISSUE THREAD

**Issue by mrkpatchaa** [lxzxl/koa-i18next-middleware#7]
TypeError: i18m.LanguageDetector.addDetector is not a function.
This happens on the application startup.

https://github.com/lxzxl/koa-i18next-middleware/blob/7936df1c7c003bbd6c00da28ad551de2a740777b/src/index.js#L6
is converted to `exports.LanguageDetector = undefined;`

**Comment by lxzxl** [comment]
@rmkpatchaa  sorry for the late response. But I cannot reproduce your issue.

**Comment by mrkpatchaa** [comment]
@lxzxl sorry this issue is quite old and I didn't touch the project for a moment.
I've let down the internationalization for now and I don't remember why I was getting this error.
So let's close this and we'll come back to it if I get the problem again.

**Comment by igorparrabastias** [comment]
@lxzxl I getting this error too.
